//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen_Axsis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios_axsis
    {
        public int id { get; set; }
        public string correo { get; set; }
        public string usuario { get; set; }
        public string contrasena { get; set; }
        public Nullable<bool> estatus { get; set; }
        public string sexo { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public string contrasena_confirm { get; set; }
    }
}
